In [1]:
##Importamos librería numpy
import numpy as np


In [2]:
##Importamos librería Panel Data
import pandas as pd
import os


In [3]:
##Importamos librería Matplotlib
import matplotlib as plt

In [4]:
#Importamos librería scikit-learn
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing



In [5]:
##importar el set de datos 
dataset = pd.read_csv("C:/Users/mgaitan/Documents/DC/daily-min-temperatures.csv",header=0)
dataset = np.array(dataset['Temp']).reshape((len(dataset), 1))
print (dataset)

[[20.7]
 [17.9]
 [18.8]
 ...
 [13.5]
 [15.7]
 [13. ]]


In [6]:
pwd

'C:\\Users\\mgaitan\\Documents'

In [7]:
##calcular la media
media_temp = dataset.mean()
print (media_temp)

11.177753424657535


In [8]:
###Calcular Desviación Estándar
desv_temp = dataset.std()
print (desv_temp)

4.071279075310806


In [9]:
### calcular vVdesv_tempalor Máximo
Valor_Max = dataset.max()
print (Valor_Max)

26.3


In [10]:
### calcular Valor Mínimo
Valor_Min = dataset.min()
print (Valor_Min)

0.0


Normalizar Manualmente

In [11]:
nm = (dataset - Valor_Min)/(Valor_Max - Valor_Min)
print('Normalización Manual',nm)

Normalización Manual [[0.78707224]
 [0.68060837]
 [0.7148289 ]
 ...
 [0.51330798]
 [0.59695817]
 [0.49429658]]


Estandarizar Manualmente

In [17]:
em = (dataset - media_temp)/desv_temp
print('Estandarización Manual',em)

Estandarización Manual [[2.33888328]
 [1.65113873]
 [1.87219948]
 ...
 [0.5703973 ]
 [1.11076801]
 [0.44758577]]


In [13]:
## Normalización scikit learn
### min Max Value ensures that no matter what scale your data is in, it will be converted to fall between the range of 0 to 1.
scaler = MinMaxScaler(feature_range=(0, 1))
normalizar = scaler.fit_transform(dataset)
for i in range(100):
    print(normalizar[i])


[0.78707224]
[0.68060837]
[0.7148289]
[0.55513308]
[0.60076046]
[0.60076046]
[0.60076046]
[0.66159696]
[0.82889734]
[0.76045627]
[0.61596958]
[0.50570342]
[0.63498099]
[0.81749049]
[0.95057034]
[0.78707224]
[0.78326996]
[0.94296578]
[0.6730038]
[0.58935361]
[0.69201521]
[0.46007605]
[0.54752852]
[0.60836502]
[0.62737643]
[0.71102662]
[0.73764259]
[0.6539924]
[0.58935361]
[0.57414449]
[0.58555133]
[0.58174905]
[0.7148289]
[0.83269962]
[0.75665399]
[0.63117871]
[0.63878327]
[0.55513308]
[0.65019011]
[0.95057034]
[0.57034221]
[0.52091255]
[0.52851711]
[0.69581749]
[0.8365019]
[0.84030418]
[0.80608365]
[0.69961977]
[0.63117871]
[0.6121673]
[0.59695817]
[0.63117871]
[0.62737643]
[0.54752852]
[0.54752852]
[0.70342205]
[0.64258555]
[0.66539924]
[0.80608365]
[0.67680608]
[0.70722433]
[0.64638783]
[0.60836502]
[0.50570342]
[0.54372624]
[0.43346008]
[0.61977186]
[0.6121673]
[0.4486692]
[0.46387833]
[0.55893536]
[0.4486692]
[0.42965779]
[0.40304183]
[0.44486692]
[0.53992395]
[0.42585551]
[0.64258

In [14]:
#Estandarizar 
## Usaré el scale : Standardize a dataset along any axis

scaled = preprocessing.scale(dataset)
print (scaled)


[[2.33888328]
 [1.65113873]
 [1.87219948]
 ...
 [0.5703973 ]
 [1.11076801]
 [0.44758577]]


In [15]:
##Sacaré la Media del Vector anterior
scaled.mean(axis=0)

array([-1.65468856e-16])

In [16]:
## Sacaré la desviación 
scaled.std(axis=0)


array([1.])